INSERT INTO BASE_RATE
(product_code, product_version, vehicle_type, fuel_type,
 engine_cc_from, engine_cc_to, zone, rate_percentage,
 effective_from, effective_to)
VALUES
('MOTOR_PC','V1','PRIVATE','PETROL',0,1000,'METRO',3.00,
 CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR)),

('MOTOR_PC','V1','PRIVATE','PETROL',0,1000,'NON_METRO',2.80,
 CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR)),

('MOTOR_PC','V1','PRIVATE','PETROL',1001,2000,'METRO',3.50,
 CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR)),

('MOTOR_PC','V1','PRIVATE','DIESEL',0,2000,'METRO',3.80,
 CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR)),

('MOTOR_PC','V1','COMMERCIAL','DIESEL',0,3000,'METRO',4.50,
 CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR));
