INSERT INTO NO_CLAIMS_DISCOUNT
(product_code, product_version,
 years_from, years_to, factor,
 effective_from, effective_to)
VALUES
('MOTOR_PC','V1',0,1,1.00, CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR)),
('MOTOR_PC','V1',2,3,0.90, CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR)),
('MOTOR_PC','V1',4,6,0.80, CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR)),
('MOTOR_PC','V1',7,8,0.70, CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR)),
('MOTOR_PC','V1',9,11,0.60, CURDATE(), DATE_ADD(CURDATE(), INTERVAL 5 YEAR));
